### ISSUE TITLE
dmaker.fan.p15 issues

### ISSUE THREAD

**Issue by Piramidowy** [syssi/xiaomi_fan#123]
After last last 2 updates (version 0.3.7 and 0.3.8) I'm getting error while setting up xiaomi_miio_fan platform.

My config:
```
fan:
  - platform: xiaomi_miio_fan
    name: Xiaomi Smart Fan Pro
    host: 192.168.x.xxx
    token: xxxxx
    model: dmaker.fan.p15
```

Error:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 231, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/xiaomi_miio_fan/fan.py", line 375, in async_setup_platform
    fan = FanP11(host, token, model=model)
  File "/usr/local/lib/python3.8/site-packages/miio/fan_miot.py", line 245, in __init__
    raise FanException("Invalid FanMiot model: %s" % model)
miio.fan_common.FanException: Invalid FanMiot model: dmaker.fan.p15
```

Home Assistant 2021.5.1 running on Docker.
Python version 3.8.9

**Comment by syssi** [comment]
I've released a hotfix. Please try again (`0.3.9`).

**Comment by syssi** [comment]
Is the info available at the Mi Home app?

**Comment by Piramidowy** [comment]
I should have checked first :)
Nope, there is no such info. That's pretty bad for battery operated fan..
