### ISSUE TITLE
Switching off oscillations

### ISSUE THREAD

**Issue by Alex0302** [syssi/xiaomi_fan#13]
Hello! Switching off oscillations does not work, switching on - works.

```
ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall fan.oscillate: entity_id=['fan.xiaomi_smart_fan'], oscillating=False>
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/core.py", line 1007, in _event_to_service_call
    await service_handler.func(service_call)
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/fan/__init__.py", line 219, in async_handle_fan_service
    yield from getattr(fan, method['method'])(**params)
  File "/home/hass/.homeassistant/custom_components/fan/xiaomi_miio_fan.py", line 502, in async_oscillate
    self._device.oscillate, False)
AttributeError: 'Fan' object has no attribute 'oscillate'
2018-06-17 23:07:31 ERROR (SyncWorker_2) [miio.fan] Count (17) of requested properties does not match the count (16) of received values.
```

**Comment by syssi** [comment]
Thanks for your feedback. I've fixed the issue. Please update the custom component!
