### ISSUE TITLE
cannot import name 'GatewayException' from 'miio.gateway'

### ISSUE THREAD

**Issue by zslibra** [syssi/xiaomi_fan#138]
hi syssi, thanks for your sharing xiaomi_miio_fan component and great job!
After enable xiaomi_miio_fan, homeassistant logged error as below, but I can control my fan as normally.
How to solve this error?
Thanks.

Homeassistant version: 2021.3.4

2021-06-12 11:29:39 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration xiaomi_miio: cannot import name 'GatewayException' from 'miio.gateway' (/usr/local/lib/python3.8/site-packages/miio/gateway/__init__.py)
2021-06-12 11:29:39 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 561, in async_create_flow
integration.get_platform("config_flow")
File "/usr/src/homeassistant/homeassistant/loader.py", line 499, in get_platform
cache[full_name] = self._import_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 504, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
File "<frozen importlib._bootstrap>", line 991, in _find_and_load
File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
File "<frozen importlib._bootstrap>", line 991, in _find_and_load
File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 783, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/__init__.py", line 5, in <module>
from miio.gateway import GatewayException
ImportError: cannot import name 'GatewayException' from 'miio.gateway' (/usr/local/lib/python3.8/site-packages/miio/gateway/__init__.py)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 122, in async_init
flow = await self.async_create_flow(handler, context=context, data=data)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 568, in async_create_flow
raise data_entry_flow.UnknownHandler
homeassistant.data_entry_flow.UnknownHandler

**Comment by syssi** [comment]
Please updated the HA core to the latest version.

**Comment by syssi** [comment]
All Xiaomi components are using the same library (`python-miio`). This custom component requires the most recent release. This version isn't compatible with your outdated HA core.

**Comment by zslibra** [comment]
Got it.
thanks.
