### ISSUE TITLE
Integration for Fan Smart Standing 3 (zhimi.fan.za5) not adding

### ISSUE THREAD

**Issue by Aliskin-Papa** [syssi/xiaomi_fan#148]
Logger: homeassistant.components.fan
Source: util/percentage.py:21
Integration: Вентилятор (documentation, issues)
First occurred: 11:17:28 (2 occurrences)
Last logged: 11:17:28

Error adding entities for domain fan with platform xiaomi_miio_fan
Error while setting up xiaomi_miio_fan platform for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 588, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 615, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 368, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 404, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 603, in state_attributes
    data[ATTR_SPEED] = self.speed
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 453, in speed
    percentage = self.percentage
  File "/config/custom_components/xiaomi_miio_fan/fan.py", line 1157, in percentage
    return ordered_list_item_to_percentage(FAN_SPEEDS_1C, self._preset_mode)
  File "/usr/src/homeassistant/homeassistant/util/percentage.py", line 21, in ordered_list_item_to_percentage
    raise ValueError(f'The item "{item}"" is not in "{ordered_list}"')
ValueError: The item "None"" is not in "['Level 1', 'Level 2', 'Level 3']"

**Comment by filikun** [comment]
Do you have the fan on the same subnet as HA? Some Xiaomi devices is very picky about this and the zhimi.fan.za5 is one of them.

**Comment by Aliskin-Papa** [comment]
> Do you have the fan on the same subnet as HA? Some Xiaomi devices is very picky about this and the zhimi.fan.za5 is one of them.

Yes, i have the fan on the same subnet as HA, 192.168.1.x

**Comment by syssi** [comment]
It looks like removing the component and re-add did solve the issue (cp. #141).
