### ISSUE TITLE
HA 2021.7.0: Error in path

### ISSUE THREAD

**Issue by andriej** [syssi/xiaomi_fan#154]
After upgrade to 2021.7 (HA) and it's Python 3.9, new error is thrown:

Logger: homeassistant.helpers.entity
Source: custom_components/xiaomi_miio_fan/fan.py:629
Integration: xiaomi_miio_fan (documentation, issues)
First occurred: 7 lipca 2021, 16:00:47 (2 occurrences)
Last logged: 9:12:51
```
Update for fan.xiaomi_fan_salon fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 401, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 609, in async_device_update
    raise exc
  File "/config/custom_components/xiaomi_miio_fan/fan.py", line 629, in async_update
    state = await self.hass.async_add_job(self._device.status)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/miio/fan.py", line 323, in status
    values = self.get_properties(properties, max_properties=_props_per_request)
  File "/usr/local/lib/python3.9/site-packages/miio/device.py", line 269, in get_properties
    values.extend(self.send(property_getter, _props[:max_properties]))
  File "/usr/local/lib/python3.9/site-packages/miio/device.py", line 178, in send
    return self._protocol.send(
  File "/usr/local/lib/python3.9/site-packages/miio/miioprotocol.py", line 194, in send
    m = Message.parse(data, token=self.token)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 288, in parse
    return self.parse_stream(io.BytesIO(data), **contextkw)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 300, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 1981, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 2439, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 4265, in _parse
    obj = self.subcon._parsereport(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 1981, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 2511, in _parse
    raise ConstError("parsing expected %r but parsed %r" % (self.value, obj), path=path)
construct.core.ConstError: Error in path (parsing) -> header
parsing expected 8497 but parsed 58287
```

**Comment by syssi** [comment]
Is this still happening? I hope the different packages/dependencies are python3.9 compatible now.
