### ISSUE TITLE
Python-miio 0.4.1 required

### ISSUE THREAD

**Issue by TribuneX** [syssi/xiaomi_fan#18]
I am trying to use the latest version of this component, but it requires version `0.4.1` of python-miio. I am getting the following error in the log:

```
Unable to install package python-miio>=0.4.1: Could not find a version that satisfies the requirement python-miio>=0.4.1
```

I assume I have to wait for version `0.4.1` to be released: https://github.com/rytilahti/python-miio/releases?

**Comment by syssi** [comment]
You need the current master of python-miio to get it working. If you are unable to install the most recent revision of python-miio manually you should wait fit the next release.

**Comment by apple4105** [comment]
But i found recent revision of python-miio is still 0.4.1,how can i get 0.4.1？

**Comment by TribuneX** [comment]
I'll wait for a python-miio release then, so I can install it with pip. Any estimation when you will release the new version?

**Comment by syssi** [comment]
Which fan model do you own? The option is called `--skip-pip`.

**Comment by apple4105** [comment]
My fan model is zhimi.fan.sa1.

**Comment by syssi** [comment]
Could you post yout configuration.yaml for the device? It looks like the wrong implementation is used. This error doesn't exist for the SA1:

`Count (17) of requested properties does not match the count (2) of received values.`

**Comment by apple4105** [comment]
My configuration is:
`fan:
    - platform: xiaomi_miio_fan
       name: xiaomi_smart_fan
       host: 192.168.198.xxx
       token: xxxxxxxxxxxxxxxxx
       model: zhimi.fan.sa1
`,and i'm sure my python-miio is the current master of python-miio,what can i do?Thx.

**Comment by syssi** [comment]
Did you install python-miio inside of your virtualenv?

**Comment by Marsmz** [comment]
I find the same error from my HA


xiaomi_miio_fan: Error on device update!
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/homeassistant/helpers/entity_platform.py", line 248, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/local/lib/python3.5/dist-packages/homeassistant/helpers/entity.py", line 317, in async_device_update
    yield from self.async_update()
  File "/home/pi/.homeassistant/custom_components/fan/xiaomi_miio_fan.py", line 413, in async_update
    self._oscillate = state.oscillate
  File "/home/pi/.homeassistant/deps/lib/python3.5/site-packages/miio/fan.py", line 143, in oscillate
    return self.data["angle_enable"] == "on"
KeyError: 'angle_enable'


Count (17) of requested properties does not match the count (2) of received values.

**Comment by syssi** [comment]
Alright. I will post some configuration to debug the custom component.

**Comment by syssi** [comment]
I checked the code and exception again. If the library complains about 17 requests properties the implementation of the zimi.fan.v3 / default is used. If you use rasbian / a virtualenv install you have to prepare your Home Assistant installation as following:

```
su - homeassistant
source /srv/homeassistant/bin/activate
pip3 install https://github.com/rytilahti/python-miio.git
/srv/homeassistant/bin/hass --skip-pip --debug
```
