### ISSUE TITLE
Count (17) of requested properties does not match the count (1) of received values

### ISSUE THREAD

**Issue by fengerzh** [syssi/xiaomi_fan#20]
Keeps getting the following error:
```
2018-08-21 07:15:45 ERROR (SyncWorker_12) [miio.fan] Count (17) of requested properties does not match the count (1) of received values.
2018-08-21 07:15:45 ERROR (MainThread) [homeassistant.helpers.entity] Update for fan.xiaomi_smart_fan fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 199, in async_update_ha_state
    yield from self.async_device_update()
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 320, in async_device_update
    yield from self.async_update()
  File "/Users/zhangjing/.homeassistant/custom_components/fan/xiaomi_miio_fan.py", line 418, in async_update
    self._oscillate = state.oscillate
  File "/Users/zhangjing/.homeassistant/deps/lib/python/site-packages/miio/fan.py", line 129, in oscillate
    return self.data["angle_enable"] == "on"
KeyError: 'angle_enable'
```

**Comment by syssi** [comment]
Please check the used version/revision of python-miio. If you've multiple xiaomi miio devices HA will downgrade the pip package to the official release.

**Comment by syssi** [comment]
I will release a new version (0.4.1) of python-miio soon. I hope this will solve the issue forever.
