### ISSUE TITLE
dmaker.fan.p39 (Smart Tower Fan) shows error when trying to configure

### ISSUE THREAD

**Issue by fribse** [syssi/xiaomi_fan#228]
HA:  2023.7.3
Integration: 2023.7.0.0

I just tried adding my two Xiaomi fans through the custom integration, instead of the cloud integration.
My old Smartmi Standing Fan 2S integrates without issues, but my neewer Smart Tower fan gives error in the log:

```
Logger: homeassistant.components.fan
Source: custom_components/xiaomi_miio_fan/fan.py:2281
Integration: Blæser (documentation, issues)
First occurred: 20.16.38 (1 occurrences)
Last logged: 20.16.38

xiaomi_miio_fan: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 570, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 940, in async_device_update
    await self.async_update()
  File "/config/custom_components/xiaomi_miio_fan/fan.py", line 2180, in async_update
    self._natural_mode = state.mode == OperationModeFanP39.Nature
                         ^^^^^^^^^^
  File "/config/custom_components/xiaomi_miio_fan/fan.py", line 2281, in mode
    return OperationModeFanP39(self.data["mode"]).name
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 711, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 1128, in __new__
    raise ve_exc
ValueError: None is not a valid OperationModeFanP39
```

**Comment by brusapa** [comment]
HA: 2023.8.2
Integration: 2023.7.0.0

I'm getting the same error with my p39 fan. Have you achieved to get it working?

**Comment by jan-sindelar** [comment]
I'm getting the same error, still not working on HA 2023.8.2 and integration 2023.7.0.0. It was discussed (and unfortunately closed) in issue #213.

**Comment by fribse** [comment]
I've had to keep it in cloud integration for the time meaning :-(
