### ISSUE TITLE
Component broke after updating home-assistant to 0.81.0

### ISSUE THREAD

**Issue by deskoh** [syssi/xiaomi_fan#23]
Component broke after updating home-assistant to 0.81.0.
Due to python-miio requirement in home-assistant bumped to [0.4.2](https://github.com/rytilahti/python-miio/releases/tag/0.4.2)

Issue can be fixed by bumping requirements to 0.4.2 as well.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/config/custom_components/fan/xiaomi_miio_fan.py", line 174, in async_setup_platform
    from miio import Device, DeviceException
  File "/config/deps/lib/python3.6/site-packages/miio/__init__.py", line 2, in <module>
    from miio.airconditioningcompanion import AirConditioningCompanion
  File "/config/deps/lib/python3.6/site-packages/miio/airconditioningcompanion.py", line 8, in <module>
    from .device import Device, DeviceException
  File "/config/deps/lib/python3.6/site-packages/miio/device.py", line 16, in <module>
    from .protocol import Message
  File "/config/deps/lib/python3.6/site-packages/miio/protocol.py", line 31, in <module>
    assert construct.version_string == "2.9.41"
AssertionError
```

**Comment by syssi** [comment]
Your `python-miio` is outdated. This line isn't part of python-miio anymore:

```
    assert construct.version_string == "2.9.41"
```

**Comment by syssi** [comment]
You could try to remove this folder and restart HA:

```
config/deps/lib/python3.6/site-packages/miio
```

The folder should be re-created with a recent version of python-miio.

**Comment by deskoh** [comment]
Yup. That fixes it.
