### ISSUE TITLE
Error while setting up platform xiaomi_miio_fan in 0.81.6

### ISSUE THREAD

**Issue by pustefix8965** [syssi/xiaomi_fan#24]
I am getting the following error after upgrading to 0.81.6. The custom component is working in 0.80.3.

```
Error while setting up platform xiaomi_miio_fan
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/config/custom_components/fan/xiaomi_miio_fan.py", line 174, in async_setup_platform
    from miio import Device, DeviceException
  File "/config/deps/lib/python3.6/site-packages/miio/__init__.py", line 2, in <module>
    from miio.airconditioningcompanion import AirConditioningCompanion
  File "/config/deps/lib/python3.6/site-packages/miio/airconditioningcompanion.py", line 8, in <module>
    from .device import Device, DeviceException
  File "/config/deps/lib/python3.6/site-packages/miio/device.py", line 16, in <module>
    from .protocol import Message
  File "/config/deps/lib/python3.6/site-packages/miio/protocol.py", line 31, in <module>
    assert construct.version_string == "2.9.41"
AssertionError
```

**Comment by syssi** [comment]
Please update Home Assistant to the latest version, delete these folders

```
/config/deps/lib/python3.6/site-packages/miio
/config/deps/lib/python3.6/site-packages/construct
```

and restart Home Assistant.

**Comment by pustefix8965** [comment]
Deleting miio folder and restart HA has resolved the issue. I do not have construct folder.
