### ISSUE TITLE
Error adding integration

### ISSUE THREAD

**Issue by vinxion** [syssi/xiaomi_fan#274]
I am getting the following error after setting up the integration, is this a known issue?

```
Error adding entity fan.xiaomi_smart_fan for domain fan with platform xiaomi_miio_fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 912, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1362, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1007, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1133, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1063, in __async_calculate_state
    capability_attr = self.capability_attributes
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 391, in capability_attributes
    supported_features = self.supported_features_compat
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 436, in supported_features_compat
    features = self.supported_features
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miio_fan/fan.py", line 730, in supported_features
    | FanEntityFeature.TURN_OFF
      ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'FanEntityFeature' has no attribute 'TURN_OFF'
```

**Comment by syssi** [comment]
The most recent HA core version is required.

**Comment by vinxion** [comment]
Thanks. I needed to remove the model name as well, it works well on auto detect!
