### ISSUE TITLE
Question: 'speed' prop value on zhimi.fan.za1

### ISSUE THREAD

**Issue by OrcaXS** [syssi/xiaomi_fan#28]
My device is zhimi.fan.za1 v2.0.3. 
The value from `get_prop "['speed']"` seems pretty weird, it keeps varying from like 400~700 even the fan speed isn't changing. `['speed_level']` does show the current speed of the fan correctly.

Enabling `homekit` with `fan:   - platform: xiaomi_miio_fan` would make hass keep complain about the `KeyError`:
```
2019-04-08 22:50:42 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/Users/orcaxs/.pyenv/versions/3.7.3/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/orcaxs/dev/hass/lib/python3.7/site-packages/homeassistant/components/homekit/type_fans.py", line 132, in update_state
    hk_speed_value = self.speed_mapping.speed_to_homekit(speed)
  File "/Users/orcaxs/dev/hass/lib/python3.7/site-packages/homeassistant/components/homekit/util.py", line 150, in speed_to_homekit
    speed_range = self.speed_ranges[speed]
KeyError: 506
```
Looks like it treats the `"['speed']"` prop as the actual speed, then turns out to be invalid. Therefore I have to create a custom fan template in order to be able to change its speed via homekit.
Is this intended or have I missed something? Thanks in advanced.

**Comment by syssi** [comment]
I will refactor the speed handling soon to be homekit complaint. This is also required to be accepted as official component: https://github.com/home-assistant/home-assistant/pull/20089

**Comment by hoangphison** [comment]
@syssi hello, any update with the PR or the update with this component? i see that PR was closed.

**Comment by syssi** [comment]
Please update the custom component and try again.
