### ISSUE TITLE
FanStatus object has no attribute 'natural_level'

### ISSUE THREAD

**Issue by syssi** [syssi/xiaomi_fan#3]
@jacekpaszkowski

```
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 244, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 325, in async_device_update
yield from self.async_update()
File "/config/custom_components/fan/xiaomi_miio_fan.py", line 391, in async_update
self._natural_mode = (state.natural_level != 0)
AttributeError: 'FanStatus' object has no attribute 'natural_level'
```

**Comment by syssi** [comment]
Please update the custom component.
