### ISSUE TITLE
is the fan problem or homkit?

### ISSUE THREAD

**Issue by skyflying5** [syssi/xiaomi_fan#38]
2019-08-07 16:10:12 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/homekit/type_fans.py", line 132, in update_state
    hk_speed_value = self.speed_mapping.speed_to_homekit(speed)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/homekit/util.py", line 156, in speed_to_homekit
    speed_range = self.speed_ranges[speed]
KeyError: 630

**Comment by syssi** [comment]
Please give it another try because we have preset support now.
