### ISSUE TITLE
Error while setting up platform xiaomi_miio_fan

### ISSUE THREAD

**Issue by CookieMonster87** [syssi/xiaomi_fan#44]
Tried the latest files updated 4 days ago and its not working. Get this error. Component was working for me before.

```
Error while setting up platform xiaomi_miio_fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/xiaomi_miio_fan/fan.py", line 258, in async_setup_platform
    device = XiaomiFan(name, fan, model, unique_id)
TypeError: __init__() missing 1 required positional argument: 'retries'
```

**Comment by syssi** [comment]
Please update the custom component and try again. :-)

**Comment by CookieMonster87** [comment]
Wow! that was a fast fix. Its working now 👍  Thanks :)
