### ISSUE TITLE
report error when file updated (xiaomi_miio_fan)

### ISSUE THREAD

**Issue by ericliu1234567** [syssi/xiaomi_fan#45]
i have updated new file and report error as below, pls help, thanks!!

fan model : zhimi.fan.za3

platform: xiaomi_miio_fan    
name: "kaylie_room_fan"    
host: 192.168.0.111    
token: 'XXXXXXXXXXXXXXXX'   

2019-10-26 21:39:02 ERROR (SyncWorker_2) [miio.fan] Count (17) of requested properties does not match the count (2) of received values.
2019-10-26 21:24:04 ERROR (MainThread) [homeassistant.components.fan] xiaomi_miio_fan: Error on device update!Traceback (most recent call last):  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 248, in _async_add_entity    await entity.async_device_update(warning=False)  File "/usr/src/app/homeassistant/helpers/entity.py", line 346, in async_device_update    await self.async_update()  File "/config/custom_components/xiaomi_miio_fan/fan.py", line 491, in async_update    self._oscillate = state.oscillate  File "/usr/local/lib/python3.7/site-packages/miio/fan.py", line 147, in oscillate    return self.data["angle_enable"] == "on"KeyError: 'angle_enable'
--

**Comment by syssi** [comment]
Which HA version do you use?

**Comment by ericliu1234567** [comment]
0.89.2

**Comment by syssi** [comment]
Please update to the latest development version. This should fix the issue.

**Comment by ericliu1234567** [comment]
Thanks!!

**Comment by terenceng81** [comment]
i have similiar issue, HA version 0.100.3.

**Comment by syssi** [comment]
Please post the content of your `__init__.py`.

**Comment by syssi** [comment]
The file should be empty if it's a copy from this repository.

**Comment by terenceng81** [comment]
it's working, thank you so much!
