### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by ericliu1234567** [syssi/xiaomi_fan#46]
i have try to update my fan.py file, but show error message after that, how to fit it? pls hlep...

 - platform: xiaomi_miio_fan
    name: "kaylie_room_fan"
    host: 192.168.0.62
    token: 'XXXXXXXXXXXXXXXXXXXXXXXXX'   

homeassistant version - 0.89.2

2019-12-12 12:10:07 ERROR (SyncWorker_9) [miio.fan] Count (17) of requested properties does not match the count (2) of received values.
2019-12-12 12:10:07 ERROR (MainThread) [homeassistant.components.fan] xiaomi_miio_fan: Error on device update!
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 248, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/app/homeassistant/helpers/entity.py", line 346, in async_device_update
    await self.async_update()
  File "/config/custom_components/xiaomi_miio_fan/fan.py", line 492, in async_update
    self._oscillate = state.oscillate
  File "/usr/local/lib/python3.7/site-packages/miio/fan.py", line 147, in oscillate
    return self.data["angle_enable"] == "on"
KeyError: 'angle_enable'

**Comment by syssi** [comment]
Which fan model do you own?

**Comment by ericliu1234567** [comment]
> Which fan model do you own?

zhimi.fan.za3, thanks!!

**Comment by syssi** [comment]
Please update the custom component and try again!
