### ISSUE TITLE
xiaomi_miio_fan error when starting HA

### ISSUE THREAD

**Issue by pasberg** [syssi/xiaomi_fan#76]
Hi,

I'm getting "Error while setting up xiaomi_miio_fan platform for fan" in my log in HA when starting HA.

Here is the traceback:
`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/xiaomi_miio_fan/fan.py", line 244, in async_setup_platform
    device_info = miio_device.info()
  File "/usr/local/lib/python3.7/site-packages/miio/device.py", line 182, in info
    return DeviceInfo(self.send("miIO.info"))
  File "/usr/local/lib/python3.7/site-packages/miio/device.py", line 147, in send
    command, parameters, retry_count, extra_parameters=extra_parameters
  File "/usr/local/lib/python3.7/site-packages/miio/miioprotocol.py", line 150, in send
    self.send_handshake()
  File "/usr/local/lib/python3.7/site-packages/miio/miioprotocol.py", line 62, in send_handshake
    header = m.header.value
AttributeError: 'NoneType' object has no attribute 'header'`

Any ideas what's going on? The integration worked yesterday...

Thanks!

**Comment by syssi** [comment]
Please update HA and this custom component.
